sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t kaitbr0/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kaitbr0/react-test npm test

after_success:
  - docker build -t kaitbr0/multi-client ./client
  - docker build -t kaitbr0/multi-server ./server
  - docker build -t kaitbr0/multi-nginx ./nginx
  - docker build -t kaitbr0/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kaitbr0/multi-client
  - docker push kaitbr0/multi-server
  - docker push kaitbr0/multi-nginx
  - docker push kaitbr0/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-2-030815009463'
    bucket_path: 'docker-multi'
    on:
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
